version: '3.8'
services:
    folio:
        build:
            context: .
            target: portfolio-cv-dev
        volumes:
            - "./:/usr/src/app"
        ports:
            - "5173:5173"
