version: '3.8'
services:
    folio:
        build: .
        restart: always
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.devleeschauwer.entrypoints=websecure
            - traefik.http.routers.devleeschauwer.rule=Host(`devleeschauwer.fr`) || Host(`www.devleeschauwer.fr`) || (Host(`omniumcorp.fr`) && PathPrefix(`/devleeschauwer`))
            - traefik.http.routers.devleeschauwer.tls.certresolver=resolver
            - traefik.http.services.devleeschauwer.loadbalancer.server.port=80
            - traefik.http.middlewares.devleeschauwer.headers.customresponseheaders.Cache-control='max-age=600'
        networks:
            - proxy
            - default

networks:
    proxy:
        external: true
    default:
        external: false
